import Link from "next/link";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-peach-50 py-12 px-6">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-terracotta-600 text-sm mb-6 inline-block hover:underline">
          ← Back to SkinScan
        </Link>

        <h1 className="font-display text-4xl text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-8">Last updated: June 2026</p>

        <div className="prose prose-gray max-w-none space-y-6 text-gray-700 text-[15px] leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using SkinScan, you agree to be bound by these Terms of Service
              and our <Link href="/privacy" className="text-terracotta-600 underline">Privacy Policy</Link>.
              If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">2. Nature of the Service</h2>
            <p>
              SkinScan provides <strong>cosmetic skin analysis only</strong>. The analysis
              is generated by artificial intelligence and is intended solely for cosmetic and
              informational purposes.
            </p>
            <div className="bg-terracotta-50 border border-terracotta-200 rounded-xl p-4 my-4">
              <p className="font-bold text-terracotta-800 mb-1">⚠️ Important Medical Disclaimer</p>
              <p className="text-terracotta-700 text-sm">
                SkinScan is <strong>NOT a medical device</strong>. It does <strong>NOT</strong> provide
                medical advice, diagnosis, or treatment. The results should not be used as a substitute
                for professional dermatological consultation. If you have a skin condition, concern
                about a mole, or any medical question, please consult a qualified dermatologist.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">3. User Consent</h2>
            <p>Before using the analysis feature, you must provide explicit consent that:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>You understand this is a cosmetic analysis tool, not medical advice.</li>
              <li>You consent to your selfie being processed by our AI model for cosmetic analysis.</li>
              <li>You understand your photo is deleted immediately after analysis unless you opt in to save it.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">4. Eligibility</h2>
            <p>
              You must be at least 18 years of age to use SkinScan. By using the service,
              you represent that you meet this requirement.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">5. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Upload images that are not selfies of your own face.</li>
              <li>Attempt to reverse-engineer, scrape, or abuse the API.</li>
              <li>Use automated tools or bots to interact with the service.</li>
              <li>Share or redistribute analysis results in a misleading manner.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">6. Intellectual Property</h2>
            <p>
              The SkinScan service, its design, and underlying technology are the intellectual
              property of the SkinScan team. Your selfie and personal data remain your property.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, SkinScan and its operators shall not be
              liable for any direct, indirect, incidental, or consequential damages arising
              from your use of the service or reliance on the analysis results.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">8. Data Deletion</h2>
            <p>
              You may request permanent deletion of all your data at any time. Upon deletion,
              your account, all analysis results, and any stored photos will be permanently
              removed from our systems.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">9. Governing Law</h2>
            <p>
              These terms are governed by the laws of India, including the Digital Personal Data
              Protection Act, 2023. Any disputes shall be subject to the exclusive jurisdiction
              of the courts in New Delhi, India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mt-8 mb-3">10. Contact</h2>
            <p>
              For questions regarding these terms, contact us at:
            </p>
            <p className="font-medium">legal@skinscan.in</p>
          </section>
        </div>
      </div>
    </div>
  );
}
